/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}",
    "./node_modules/preline/preline.js",
  ],
  theme: {
    fontFamily: {
      sans: [
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica",
        "Arial",
        "sans-serif",
      ],
      serif: [
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Georgia",
        "Cambria",
        "Times New Roman",
        "serif",
      ],
      mono: [
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
    extend: {
      backgroundImage: {
        "gradient-to-t":
          "linear-gradient(to top, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 100%)",
        transparent:
          "linear-gradient(to top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%)",
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            a: {
              color: theme("colors.blue.500"),
              textDecoration: "none",
              "&:hover": {
                color: theme("colors.blue.700"),
                textDecoration: "underline",
              },
            },
            sup: {
              fontSize: "inherit",
              verticalAlign: "baseline !important",
              position: "static",
              color: theme("colors.blue.500"),
              "&::before": { content: '"["' },
              "&::after": { content: '"]"' },
              "&:hover": {
                textDecoration: "underline",
                color: theme("colors.blue.700"),
              },
            },
            "a.footnote-ref": {
              "&::before": { content: '"["' },
              "&::after": { content: '"]"' },
            },
            code: {
              color: theme("colors.pink.600"),
              backgroundColor: theme("colors.neutral.100"),
              borderRadius: theme("borderRadius.sm"),
              paddingLeft: theme("spacing[1.5]"),
              paddingRight: theme("spacing[1.5]"),
              paddingTop: theme("spacing[0.5]"),
              paddingBottom: theme("spacing[0.5]"),
              fontWeight: "400",
            },
            "code::before": { content: "none" },
            "code::after": { content: "none" },
            "pre code": { backgroundColor: "transparent", padding: "0", borderRadius: "0" },
            maxWidth: "80ch", // Increase prose width by ~20% from default 65ch
            // GitHub link styling
            'a[href*="github.com"]': {
              position: "relative",
              paddingLeft: "1.30rem",
              "&::before": {
                content: '""',
                position: "absolute",
                left: "0.1rem",
                top: "50%",
                transform: "translateY(-50%)",
                width: "1rem",
                height: "1rem",
                backgroundImage: 'url("/src/assets/github-icon.svg")',
                backgroundSize: "contain",
                backgroundRepeat: "no-repeat",
                backgroundPosition: "center",
              },
            },
            // Callout box styling
            ".tldr": {
              backgroundColor: "#f9f8f7",
              border: "none",
              borderLeft: "none",
              borderRadius: "0.5rem",
              padding: "0.75rem",
              marginTop: "0.5rem",
              marginBottom: "0.25rem",
              color: "#374151",
              position: "relative",
            },
            ".tldr::before": {
              content: '"💡 TL;DR"',
              display: "block",
              fontWeight: "600",
              fontSize: "1.125rem",
              marginBottom: "0.25rem",
              color: "#374151",
              marginLeft: "-0.75rem",
              paddingLeft: "0.75rem",
            },
            ".tldr p": {
              paddingLeft: "1.5rem",
              margin: "0",
            },
            ".note": {
              backgroundColor: "#f8f8f8",
              border: "none",
              borderLeft: "none",
              borderRadius: "0.5rem",
              padding: "0.75rem",
              marginTop: "0.5rem",
              marginBottom: "0.5rem",
              color: "#374151",
              position: "relative",
            },
            ".note::before": {
              content: '"📝 Note"',
              display: "block",
              fontWeight: "600",
              fontSize: "1.125rem",
              marginBottom: "0.25rem",
              color: "#374151",
            },
            ".note p": {
              paddingLeft: "1.5rem",
              margin: "0",
            },
            ".quote": {
              backgroundColor: "transparent",
              border: "none",
              borderLeft: "4px solid #000",
              borderRadius: "0",
              padding: "0.75rem",
              paddingLeft: "1rem",
              marginTop: "0.5rem",
              marginBottom: "0.5rem",
              color: "#374151",
              position: "relative",
              fontStyle: "italic",
            },
            ".quote p": {
              paddingLeft: "0",
              margin: "0",
            },
          },
        },
        dark: {
          css: {
            a: {
              color: theme("colors.blue.400"),
              textDecoration: "none",
              "&:hover": {
                color: theme("colors.blue.600"),
                textDecoration: "underline",
              },
            },
            sup: {
              fontSize: "inherit",
              verticalAlign: "baseline !important",
              position: "static",
              color: theme("colors.blue.400"),
              "&::before": { content: '"["' },
              "&::after": { content: '"]"' },
              "&:hover": {
                textDecoration: "underline",
                color: theme("colors.blue.600"),
              },
            },
            "a.footnote-ref": {
              "&::before": { content: '"["' },
              "&::after": { content: '"]"' },
            },
            code: {
              color: theme("colors.pink.400"),
              backgroundColor: theme("colors.neutral.800"),
              borderRadius: theme("borderRadius.sm"),
              paddingLeft: theme("spacing[1.5]"),
              paddingRight: theme("spacing[1.5]"),
              paddingTop: theme("spacing[0.5]"),
              paddingBottom: theme("spacing[0.5]"),
              fontWeight: "400",
            },
            "code::before": { content: "none" },
            "code::after": { content: "none" },
            "pre code": { backgroundColor: "transparent", padding: "0", borderRadius: "0" },
            maxWidth: "80ch", // Increase prose width by ~20% from default 65ch
            // GitHub link styling
            'a[href*="github.com"]': {
              position: "relative",
              paddingLeft: "1.30rem",
              "&::before": {
                content: '""',
                position: "absolute",
                left: "0.1rem",
                top: "50%",
                transform: "translateY(-50%)",
                width: "1rem",
                height: "1rem",
                backgroundImage: 'url("/src/assets/github-icon.svg")',
                backgroundSize: "contain",
                backgroundRepeat: "no-repeat",
                backgroundPosition: "center",
              },
            },
            // Callout box styling
            ".tldr": {
              backgroundColor: "#f9f8f7",
              border: "none",
              borderLeft: "none",
              borderRadius: "0.5rem",
              padding: "0.75rem",
              marginTop: "0.5rem",
              marginBottom: "0.25rem",
              color: "#374151",
              position: "relative",
            },
            ".tldr::before": {
              content: '"💡 TL;DR"',
              display: "block",
              fontWeight: "600",
              fontSize: "1.125rem",
              marginBottom: "0.25rem",
              color: "#374151",
              marginLeft: "-0.75rem",
              paddingLeft: "0.75rem",
            },
            ".tldr p": {
              paddingLeft: "1.5rem",
              margin: "0",
            },
            ".note": {
              backgroundColor: "#f8f8f8",
              border: "none",
              borderLeft: "none",
              borderRadius: "0.5rem",
              padding: "0.75rem",
              marginTop: "0.5rem",
              marginBottom: "0.5rem",
              color: "#374151",
              position: "relative",
            },
            ".note::before": {
              content: '"📝 Note"',
              display: "block",
              fontWeight: "600",
              fontSize: "1.125rem",
              marginBottom: "0.25rem",
              color: "#374151",
            },
            ".note p": {
              paddingLeft: "1.5rem",
              margin: "0",
            },
            ".quote": {
              backgroundColor: "transparent",
              border: "none",
              borderLeft: "4px solid #000",
              borderRadius: "0",
              padding: "0.75rem",
              paddingLeft: "1rem",
              marginTop: "0.5rem",
              marginBottom: "0.5rem",
              color: "#374151",
              position: "relative",
              fontStyle: "italic",
            },
            ".quote p": {
              paddingLeft: "0",
              margin: "0",
            },
          },
        },
      }),
    },
  },
  plugins: [require("preline/plugin"), require("@tailwindcss/typography")],
};
